"use client"
import type { Metadata } from "next";
import "./globals.css";
import { usePathname } from "next/navigation";



// export const metadata: Metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  
  export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const pathName = usePathname()
  
  return (
    <html lang="en">
      <body>

      {/* Render the layout conditionally */}
        {(pathName !== '/register') && (pathName !== '/login')
        ? <><h1 className="HomeLayout" > Home page Layout...</h1></>
        : null
        }
        
        {children}

      
        </body>
    </html>
  );
}
